"""add_timezone_to_users

Revision ID: 8705d827fc13
Revises: bb75b3157944
Create Date: 2026-03-13 17:41:23.902914

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8705d827fc13"
down_revision: Union[str, Sequence[str], None] = "bb75b3157944"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###
