"""initial schema

Revision ID: bb75b3157944
Revises: 
Create Date: 2026-03-13 10:29:57.103046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb75b3157944'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emeralds', sa.Integer(), nullable=False),
    sa.Column('trading_hall_level', sa.Integer(), nullable=False),
    sa.Column('last_roll_at', sa.Integer(), nullable=True),
    sa.Column('last_claim_at', sa.Integer(), nullable=True),
    sa.Column('last_focus_roll_at', sa.Integer(), nullable=True),
    sa.Column('last_reroll_at', sa.Integer(), nullable=True),
    sa.Column('last_daily_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('collections',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mob_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['users.guild_id', 'users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'mob_id')
    )
    op.create_table('inventory',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['users.guild_id', 'users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('collections')
    op.drop_table('users')
    # ### end Alembic commands ###
